[UPDATE] Babel, ESLint, Jest, Prettier

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,3 +1,7 @@
 #!/bin/bash
 
-node ./dist/app.js
+if [ -f 'lib/app.js' ]; then
+  node lib/app.js
+else
+  echo -e "\E[1;31mERROR: App not built.\E[1;37m" && exit 1
+fi
